### ISSUE TITLE
Breaking sentences - feature request

### ISSUE THREAD

**Issue by stovepot** [TopShelfCraft/Wordsmith-Docs#1]
is it possible to "<br>" an entry.title?

**Example**:

This long title might not fit in the slide window.

This long title
might not fit 
in the slide window.

I guess this requires certain specific parameters e.g. <br> every 3rd word, etc…

**Comment by michaelrog** [comment]
Moved this Issue to the plugin repo: https://github.com/TopShelfCraft/Wordsmith/issues/3
