### ISSUE TITLE
Unknown argument "words" for filter "hacksaw(unit, limit, allowed_tags, append)"

### ISSUE THREAD

**Issue by shantamg** [TopShelfCraft/Wordsmith-Docs#2]
I had been using the hacksaw plugin with Craft 2 and was doing this:

    hacksaw(words='30')

After upgrading to Craft 3 and installing Wordsmith, Craft raises raises an unknown argument error.
It's an easy fix, just need to change it to

    hacksaw(unit='words', limit='30')

but I thought I'd mention it because this a case where Wordsmith is not backwards compatible with hacksaw.

**Comment by michaelrog** [comment]
Thanks for catching this! We should definitely add some param normalization there for backwards compatibility.

**Comment by shantamg** [comment]
Am I correct that you have not made the source public? Can't find it anywhere otherwise I would have opened the issue there and perhaps done a PR.

**Comment by michaelrog** [comment]
Doh, I didn't realize this Issue is on the documentation repo. Have re-created the issue over on the plugin repo: https://github.com/TopShelfCraft/Wordsmith/issues/2

Sorry for the confusion!
